name: CI

on:
#  pull_request:
#    branches:
#      - '*'
  push:
    branches:
      - 'main'
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Copy files
        run: rsync -aWz --progress --exclude=.git* ./ /home/ubuntu/prostavushka_bot/

      # Runs a set of commands using the runners shell
      - name: Restart supervisord service
        run: sudo systemctl restart supervisord.service

      - name: Send failure notifications to Telegram
        if: ${{ failure() }}
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT }} -d text="${MESSAGE}" >> /dev/null
        env:
          MESSAGE: "CI failed"

      - name: Send success notifications to Telegram
        if: ${{ success() }}
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT }} -d text="${MESSAGE}" >> /dev/null
        env:
          MESSAGE: "I'm just successfuly updated"
